#!/bin/sh

# The directory containing jacl.jar and tcljava.jar
JACL_DIR=.

# The directory containing swank.jar
SWANK_DIR=.

# Fully qualified path name of JVM executable
JAVA=java

# The arguments to the JAVA command
JAVA_FLAGS=" -ms32m -mx64m"

CLASSPATH=${SWANK_DIR}/swank.jar:${JACL_DIR}/jacl.jar:${JACL_DIR}/tcljava.jar
export CLASSPATH
exec ${JAVA} ${JAVA_FLAGS} tcl.lang.SwkShell resource:/com/onemoonscientific/swank/library/startconsole.tcl
