#!/bin/sh

# The directory containing jacl.jar and tcljava.jar
JACL_DIR=../../libs


# The directory containing swank.jar
SWANK_DIR=./dist/lib


# Fully qualified path name of JVM executable
JAVA=java

# The arguments to the JAVA command
JAVA_FLAGS=" -ms32m -mx64m"

CLASSPATH=${SWANK_DIR}/swank.jar:${JACL_DIR}/jacl.jar:${JACL_DIR}/tcljava.jar:${JACL_DIR}/tjc.jar:${JACL_DIR}/janino.jar:${JACL_DIR}/itcl.jar:${SWANK_DIR}/swankchart.jar:${JACL_DIR}/jcommon.jar:${JACL_DIR}/jfreechart.jar
export CLASSPATH
exec ${JAVA} ${JAVA_FLAGS} tcl.lang.SwkShell ${1+"$@"}
