#!/bin/sh

# swank [ script  [ arg ... ] ]
# 
# optional environment variables:
#
# JAVA_HOME  - directory of JDK/JRE, if not set then 'java' must be found on PATH
# CLASSPATH  - colon separated list of additional jar files & class directories
# JAVA_OPTS  - list of JVM options, e.g. "-Xmx256m -Dfoo=bar"
# TCLLIBPATH - space separated list of Tcl libraries directories
#

swankver=3.0.0-a1
swankmain=tcl.lang.SwkShell

iscygwin=false
ismsys=false
case "`uname`" in
    CYGWIN*) iscygwin=true ;;
    MINGW*) ismsys=true ;;
esac

JAVA=java
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java"  ] ; then
        # AIX location
        JAVA="$JAVA_HOME/jre/sh/java"
    else
        JAVA="$JAVA_HOME/bin/java"
    fi
fi

# get the directory path of this script
# resolve script symlink, if any
pgm="$0"
while [ -h "$pgm" ]; do
    ls=`ls -ld "$pgm"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        pgm="$link"
    else
        pgm=`dirname "$PRG"`/"$link"
    fi
done

dir=`dirname $pgm`

# set classpath, or add to existing
if [ -z "$CLASSPATH" ] ; then
    CLASSPATH="$dir/swank-$swankver.jar:$dir/jcommon-1.0.16.jar:$dir/jfreechart-1.0.13.jar"
    if $iscygwin ; then
        CLASSPATH=`cygpath -pw "$CLASSPATH"`
    fi
else
    if $ismsys ; then
        swankdir=`$dir/echopath $dir`
        CLASSPATH="$swankdir/swank-$swankver.jar;$dir/jcommon-1.0.16.jar;$dir/jfreechart-1.0.13.jar;$CLASSPATH"
    elif $iscygwin ; then
        CLASSPATH=`cygpath -pu "$CLASSPATH"`
        CLASSPATH="$dir/swank-$swankver.jar;$dir/jcommon-1.0.16.jar;$dir/jfreechart-1.0.13.jar;$CLASSPATH"
        CLASSPATH=`cygpath -pw "$CLASSPATH"`
    else 
        CLASSPATH="$dir/swank-$swankver.jar:$dir/jcommon-1.0.16:$dir/jcommon-1.0.16:$CLASSPATH"
    fi
fi

export CLASSPATH

exec "$JAVA" -DTCLLIBPATH="$TCLLIBPATH" -cp "$CLASSPATH" $JAVA_OPTS $swankmain ${1+"$@"}
